// question 10

  let favoriteCars = ["Tesla Model S", "Porsche 911", "Audi R8", "BMW M3", "Mercedes-Benz S-Class"];

  console.log("First index of the array: " + favoriteCars[0]);

  console.log("Car at first index of the array: " + favoriteCars[0]);

  console.log("Last index of the array: " + (favoriteCars.length - 1));

  console.log("Car at last index of the array: " + favoriteCars[favoriteCars.length - 1]);